# Generated by Django 5.1 on 2024-08-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('academicSectionId', models.IntegerField()),
                ('courseId', models.IntegerField()),
                ('academicSessionId', models.IntegerField()),
                ('courseCode', models.CharField(max_length=10)),
                ('courseTitle', models.CharField(max_length=255)),
                ('courseDetails', models.CharField(max_length=255)),
                ('empName', models.CharField(max_length=255)),
                ('empShortName', models.CharField(max_length=10)),
                ('deptName', models.CharField(max_length=255)),
                ('classSchedule', models.TextField()),
                ('classLabSchedule', models.TextField()),
                ('preRequisiteCourses', models.TextField(blank=True)),
                ('defaultSeatCapacity', models.IntegerField()),
                ('availableSeat', models.IntegerField()),
                ('totalFillupSeat', models.IntegerField()),
                ('courseCredit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dayNo', models.CharField(max_length=50)),
            ],
        ),
    ]
